### ISSUE TITLE
jQuery selector missing .

### ISSUE THREAD

**Issue by resonantdoghouse** [redacademy/best-spring-2019#11]
I'm not sure where this is on the site however I suspect this line of code will return a null value as it looks like you are grabbing an element which doesn't exist but the class might, you just need to add a `.`

https://github.com/redacademy/best-spring-2019/blob/52905a919109e2d48b052f5a3ca5acc15028dbd0/themes/best-bc/js/script.js#L81

**Comment by Penner77** [comment]
Resolved
