### ISSUE TITLE
Navigation not working for both desktop and mobile

### ISSUE THREAD

**Issue by ypantig** [redacademy/best-spring-2019#2]
Clicking on a submenu for desktop doesn't take the user to the corresponding page (for example History). 

For mobile, the submenu is not working as well. It opens up the navigation, but clicking the submenu closes the main menu.

**Comment by resonantdoghouse** [comment]
I think the issue is this line: https://github.com/redacademy/best-spring-2019/blob/52905a919109e2d48b052f5a3ca5acc15028dbd0/themes/best-bc/js/script.js#L34

If you change the selector that you are clicking on to be `.hamburger-menu` instead it should help to fix this issue.

**Comment by tenzyy** [comment]
Vincent currently working on it
