### ISSUE TITLE
Consider moving this to the _front-page.scss

### ISSUE THREAD

**Issue by ypantig** [redacademy/best-spring-2019#3]
There's a comment above this line that says `front-page`. Might be best to move this over to `_front-page.scss` to keep things organized and easy to find if it is just for the front page.

https://github.com/redacademy/best-spring-2019/blob/52905a919109e2d48b052f5a3ca5acc15028dbd0/themes/best-bc/sass/_page-templates.scss#L26-L30

**Comment by tenzyy** [comment]
moved
