### ISSUE TITLE
Can't nest h2 within a button

### ISSUE THREAD

**Issue by ypantig** [redacademy/best-spring-2019#6]
At the moment, the button has an h2 tag within it. To fix this, maybe consider creating a `.h2` class that has the exact same styles as `h2` and use a `span` tag, for example, inside the the button with this class.

https://github.com/redacademy/best-spring-2019/blob/52905a919109e2d48b052f5a3ca5acc15028dbd0/themes/best-bc/page-history.php#L28-L30

**Comment by tenzyy** [comment]
changed h2 to p
