### ISSUE TITLE
Remove extra `p` tag

### ISSUE THREAD

**Issue by ypantig** [redacademy/best-spring-2019#7]
In the CMS, it looks like the `tab_body` field is a WYSIWYG, which automatically generates `p` tags. Wrapping this line in `p` creates an unnecessary extra `p` tag in the DOM.

https://github.com/redacademy/best-spring-2019/blob/52905a919109e2d48b052f5a3ca5acc15028dbd0/themes/best-bc/page-history.php#L35

https://github.com/redacademy/best-spring-2019/blob/52905a919109e2d48b052f5a3ca5acc15028dbd0/themes/best-bc/page-get-involved.php#L42

Note: looks like this is happening on all instances of `tab_body`. Please check page templates to make sure.

**Comment by Penner77** [comment]
Found 3 conflicts total, resolved.
