### ISSUE TITLE
Image naming convention

### ISSUE THREAD

**Issue by ypantig** [redacademy/best-spring-2019#9]
Consider renaming the images to all lowercase and no spaces in between. If there is a need to separate words, use a `-` in between instead of spaces.

For example: `HomepageSponsorCard.jpg` to `homepage-sponsor-card.jpg` or `homepagesponsorcard.jpg`

**Comment by Penner77** [comment]
In this case, we have ensured our file names are correct but will not have time to go through and re-name all image files but completely agree. This was discussed with Jim Bennett on a few occasions.
